#!/usr/bin/env node
/**
 * Regenerates lib/blur.ts, the inline LQIP placeholder behind every photo.
 * Run after dropping new images into /public:  npm run blur
 */
import sharp from "sharp";
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PUBLIC = "public";
const OUT = "lib/blur.ts";
const IMAGES = /\.(jpe?g|png|webp|avif)$/i;

const files = readdirSync(PUBLIC).filter((f) => IMAGES.test(f)).sort();
if (!files.length) {
  console.error("No images in /public");
  process.exit(1);
}

const entries = [];

for (const file of files) {
  try {
    const buf = await sharp(join(PUBLIC, file))
      .resize(24, 24, { fit: "inside" })
      .jpeg({ quality: 45, chromaSubsampling: "4:2:0" })
      .toBuffer();

    const uri = `data:image/jpeg;base64,${buf.toString("base64")}`;
    if (uri.length > 4000) {
      console.warn(`! ${file} placeholder unexpectedly large (${uri.length}) — skipped`);
      continue;
    }
    entries.push([`/${file}`, uri]);
    console.log(`✓ ${file.padEnd(26)} ${String(buf.length).padStart(5)} B`);
  } catch (err) {
    console.warn(`⨯ ${file}: ${err.message}`);
  }
}

writeFileSync(
  OUT,
  `// Generated by scripts/blur.mjs — run \`npm run blur\` after adding photos.

export const blurData: Record<string, string> = {
${entries.map(([k, v]) => `  ${JSON.stringify(k)}:\n    ${JSON.stringify(v)},`).join("\n")}
};
`
);

const total = entries.reduce((n, [, v]) => n + v.length, 0);
console.log(`\n${OUT}: ${entries.length} placeholders, ${(total / 1024).toFixed(1)} KB inlined.`);
